server:
  port: 8080

spring:
  profiles:
    active: local

logging:
  level:
    org.example: INFO
    software.amazon.awssdk: WARN

aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET}