logging:
  level:
    org.example: DEBUG
    software.amazon.awssdk: DEBUG

aws:
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ${AWS_S3_BUCKET}